language: php

php:
  - 5.3

mysql:
  database: restful_search_api
  username: root
  encoding: utf8

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd ../..

  # install drush
  - pear channel-discover pear.drush.org
  - pear install drush/drush-5.8.0
  - phpenv rehash

  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get update > /dev/null
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # create new site, stubbing sendmail path with true to prevent delivery errors and manually resolving drush path
  - mysql -e 'create database restful_search_api'
  - php -d sendmail_path=`which true` `pear config-get php_dir`/drush/drush.php --yes core-quick-drupal --profile=testing --no-server --db-url=mysql://root:@127.0.0.1/restful_search_api --enable=simpletest restful_search_api

  # reference and enable restful_search_api in build site
  - ln -s $(readlink -e $(cd -)) restful_search_api/drupal/sites/all/modules/restful_search_api
  - cd restful_search_api/drupal
  - drush dl restful --yes
  - drush --yes pm-enable restful_search_api restful_search_api_test

  # Download entity validator.
  - drush dl entity_validator --dev --yes

  # Patch Entity API.
  - curl -O https://www.drupal.org/files/issues/2086225-entity-access-check-node-create-3.patch
  - patch -p1 /home/travis/build/restful_search_api/drupal/sites/all/modules/entity/modules/callbacks.inc < 2086225-entity-access-check-node-create-3.patch

  # start a web server on port 8080, run in the background; wait for initialization
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script: drush test-run "RESTful Search API" --uri=http://127.0.0.1:8080
